### ISSUE TITLE
Ansible 2.0

### ISSUE THREAD

**Issue by kostyrev** [hudecof/ansible_users#4]
Hi, Peter!
Now, there's Ansible 2.0 everywhere.
And I think new version isn't that backward-compatible.
And for our changes to group creation to work we need to introduce backward-incompatible changes:
https://github.com/kostyrevaa/ansible_users/compare/master...kostyrevaa:ansible2

what you think?

At least, I think they are not backward-compatible, maybe we didn't write group removal task correctly in the first place.

**Comment by hudecof** [comment]
Hi,
I swithched to ansible 2 on most of my installations nad rewriting the roles as needed. So far I did not userd user managment role.
I can create TAG for 1.X version, the latest HEAD will be compatible for lastest ansible.

**Comment by kostyrev** [comment]
So you don't mind me sending that MR?

**Comment by hudecof** [comment]
No, send it, but take me time to test it.

**Comment by kostyrev** [comment]
Closing for it was merged in https://github.com/hudecof/ansible_users/pull/5
